# Generated by Django 5.0 on 2024-03-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
